[package]
name = "vk-ffi"
description = "Direct, complete bindings to the Vulkan API"
version = "0.1.0"
authors = ["Matthew McAllister <matthew.mcallister.0@gmail.com>"]
edition = "2018"

[dependencies]
