[package]
name = "vk-ffi"
description = "Complete, direct bindings to the Vulkan API"
version = "0.1.88"
authors = ["Matthew McAllister <matthew.mcallister.0@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.42"
